# See https://github.com/prometheus/prometheus/blob/release-2.45/documentation/examples/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: jenkins-server
    metrics_path: /prometheus
    scheme: http
    static_configs:
      - targets: ["jenkins-server:8080"]

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: vault-proxy
    metrics_path: /proxy/v1/metrics
    params:
      format: [prometheus]
    scheme: http
    authorization:
      credentials_file: /vault/secrets/metrics/.vault-token
    static_configs:
      - targets: ["vault-proxy:8200"]

  - job_name: vault-server
    metrics_path: /v1/sys/metrics
    params:
      format: [prometheus]
    scheme: http
    authorization:
      credentials_file: /vault/secrets/metrics/.vault-token
    static_configs:
      - targets: ["vault-server:8200"]
